import numpy as np

from numpy.typing import NDArray
from typing import TypeAlias
from numba import njit
from collections.abc import Callable


BoundaryProcess: TypeAlias = Callable[
    [
        NDArray,  # t_eval
        NDArray,  # x_store
        float,  # t_before_breach
        float,  # t_after_breach
        NDArray,  # state_before_breach
        NDArray,  # state_after_breach
        int,  # next_store_index
        int,  # n_nodes
        NDArray,  # r
        NDArray,  # r_tilde
    ],
    tuple[NDArray, float, NDArray, int, bool],
]


@njit(cache=True)
def clip_to_boundary(
    _t_eval: NDArray,
    x_store: NDArray,
    _t_before_breach: float,
    t_after_breach: float,
    _state_before_breach: NDArray,
    state_after_breach: NDArray,
    next_store_index: int,
    _n_nodes: int,
    _r: NDArray,
    _r_tilde: NDArray,
) -> tuple[NDArray, float, NDArray, int, bool]:
    """
    Cuts of any negative/larger than 1 values and renormalizes the resulting clipped vector.

    This function has no theoretical justification.
    It is easy and fast.
    Does not advance time.

    Parameters
    ----------
    _t_eval: NDArray, unused
    x_store: NDArray
        Shape = (num_time_steps, n_states)
    _t_before_breach: float, unused
    t_after_breach: float
    _state_before_breach: NDArray, unused
    state_after_breach: NDArray
        Shape = (n_states,)
    next_store_index: int
    _n_nodes: int, unused
    _r: NDArray, unused
    _r_tilde: NDArray, unused

    Returns
    -------
    tuple[NDArray, float, NDArray, int, bool]
            (x_store, current_t, current_share, save_index, advances_time)
            advances_time=False
    """
    clipped_state = np.clip(state_after_breach, 0, 1)
    clipped_state /= np.sum(clipped_state)

    return x_store, t_after_breach, clipped_state, next_store_index, False


def compute_boundary_mfe_reflection(
    _t_eval: NDArray,
    x_store: NDArray,
    _t_before_breach: float,
    t_after_breach: float,
    _state_before_breach: NDArray,
    state_after_breach: NDArray,
    next_store_index: int,
    n_nodes: int,
    r: NDArray,
    r_tilde: NDArray,
) -> tuple[NDArray, float, NDArray, int, bool]:
    """
    Ansatz Gradient Descent
    Parameters
    ----------
    _t_eval
    x_store
    _t_before_breach
    t_after_breach
    _state_before_breach
    state_after_breach
    next_store_index
    n_nodes
    r
    r_tilde

    Returns
    -------

    """

    x_tmp = _project_onto_standard_simplex(state_after_breach)

    # Until now assumption that x_tmp is in the inner of the boundary face.

    boundary_face_index = np.argmin(x_tmp)  # projection has to have zero entry
    n_states = state_after_breach.shape[0]
    corner_point = np.zeros(n_states)
    corner_point[boundary_face_index] = 1
    face_normal_vector = np.full(n_states, 1 / n_states) - corner_point

    face_normal_vector = np.zeros((2, n_states))
    face_normal_vector[0, :] = 1.0
    face_normal_vector[1, boundary_face_index] = 1

    projection_matrix = (
        np.eye(n_states)
        - face_normal_vector.T
        @ np.linalg.inv(face_normal_vector @ face_normal_vector.T)
        @ face_normal_vector
    )

    print(projection_matrix)

    # Start of gradient descent loop
    mfe_x = _compute_mean_field_equation(x_tmp, r, r_tilde)
    mfe_x_jacobian = _compute_mean_field_equation_jacobian(x_tmp, r, r_tilde)

    line_projection_vector = _compute_projection_onto_line_vector(
        x_tmp, mfe_x, state_after_breach
    )

    residual = 0.5 * np.dot(line_projection_vector.T, line_projection_vector)

    print("residual: ", residual)

    residual_jacobian = _compute_line_point_projection_jacobian(
        x_tmp, mfe_x, mfe_x_jacobian, state_after_breach
    )

    print("residual jacobian: \n", residual_jacobian)
    # Project jacobian onto hyperplane generated by simplex face

    projected_residual_jacobian = residual_jacobian @ projection_matrix

    print(projected_residual_jacobian @ face_normal_vector[1, :])

    print("projected residual jacobian: \n", projected_residual_jacobian)

    print(projected_residual_jacobian.T @ face_normal_vector.T)

    # line search

    x = 213

    return x_store, t_after_breach, x, next_store_index, False


def _compute_mean_field_equation(
    shares: NDArray, r: NDArray, r_tilde: NDArray
) -> NDArray:

    n_states = shares.shape[0]
    res = np.zeros(n_states)
    for m in range(n_states):
        for n in range(n_states):
            if m == n:
                continue
            tmp = shares[m] * (r[m, n] * shares[n] + r_tilde[m, n])
            res[n] += tmp
            res[m] -= tmp
    return res


@njit(cache=True)
def _compute_mean_field_equation_jacobian(
    shares: NDArray, r: NDArray, r_tilde: NDArray
) -> NDArray:
    """
    Analytically computes the jacobian of the mean field equation.

    Parameters
    ----------
    shares : NDArray
        shape = (n_states, )
    r : NDArray
        shape = (n_states, n_states)
    r_tilde : NDArray
        shape = (n_states, n_states)

    Returns
    -------
    NDArray
        shape = (n_states, n_states)
    """

    n_states = shares.shape[0]
    jacobi = np.zeros((n_states, n_states))
    for i in range(n_states):
        for j in range(n_states):
            if i == j:
                for k in range(n_states):
                    if k == i:
                        continue
                    jacobi[i, j] += shares[k] * (r[i, k] - r[k, i]) + r_tilde[i, k]
                continue
            jacobi[i, j] = shares[i] * (r[i, j] - r[j, i]) - r_tilde[j, i]

    return jacobi


@njit(cache=True)
def _compute_projection_onto_line_vector(
    line_base_point: NDArray, line_vector: NDArray, point: NDArray
) -> NDArray:
    """
    Computes the vector that points from point to its projection on the line.

    The line is defined by a base vector and a direction vector.
    Take the norm of the result to get the distance between the point and the line.

    Parameters
    ----------
    line_base_point: NDArray
    line_vector: NDArray
        Does not have to be unit length.
    point: NDArray

    Returns
    -------
    projection_vector: NDArray
    """
    return (
        line_base_point
        - point
        - ((line_base_point - point) @ line_vector) * line_vector
    )


@njit(cache=True)
def _compute_line_point_distance(
    line_base_point: NDArray, line_vector: NDArray, point: NDArray
) -> float:
    """
    Computes the distance between a line defined by a base point and a vector and a point.

    Input arrays have to have dtype float or complex since numba cannot handle exotic dtypes like int.

    Parameters
    ----------
    line_base_point: NDArray
    line_vector: NDArray
        Does not have to be unit length.
    point: NDArray

    Returns
    -------
    distance: float
    """
    line_vector = line_vector / np.linalg.norm(line_vector)
    return float(
        np.linalg.norm(
            line_base_point
            - point
            - ((line_base_point - point) @ line_vector) * line_vector,
            2,
        )
    )


@njit(cache=True)
def _compute_line_point_projection_jacobian(
    line_base_point: NDArray,
    line_vector: NDArray,
    vector_field_jacobian: NDArray,
    point: NDArray,
) -> NDArray:
    """
    Computes the Jacobian of the distance of a point to a line defined by a vector field.

    See _compute_projection_onto_line_vector for the corresponding projection function.

    Parameters
    ----------
    line_base_point: NDArray
    line_vector: NDArray
    vector_field_jacobian: NDArray
    point: NDArray

    Returns
    -------
    Jacobian: NDArray
    """
    n_states = line_vector.shape[0]

    res_jacobi = np.zeros((n_states, n_states))

    for i in range(n_states):
        for j in range(n_states):
            if i == j:
                res_jacobi[i, j] += 1
            res_jacobi[i, j] += (
                -line_vector[j] * line_vector[i]
                - ((line_base_point - point) @ vector_field_jacobian[i, :])
                * line_vector[i]
                - ((line_base_point - point) @ line_vector)
                * vector_field_jacobian[i, j]
            )

    return res_jacobi


@njit(cache=True)
def compute_normal_boundary_reflection(
    _t_eval: NDArray,
    x_store: NDArray,
    _t_before_breach: float,
    t_after_breach: float,
    _state_before_breach: NDArray,
    state_after_breach: NDArray,
    next_store_index: int,
    n_nodes: int,
    _r: NDArray,
    _r_tilde: NDArray,
) -> tuple[NDArray, float, NDArray, int, bool]:
    """
    Computes the reflection with respect to the normal of the boundary.

    This function is well-defined for all input values.
    The best approximation to state_after_breach on the simplex is used as reflection point.
    The reflection is adapted if the formally correct reflected point is outside the simplex.
    Does not advance time.

    Purpose of this function is to approximate the MFE-reflection.
    Formally undefined cases are solved with this purpose in mind.
    This works best if the rates are somewhat balanced, i.e., r[i,j] \approx r[j,i] (same for r_tilde).
    For non balanced rates, an oblique reflection into the (per boundary face) average direction
    of the MFE on the boundary could be used.

    Parameters
    ----------
    _t_eval: NDArray, unused
    x_store: NDArray
        Shape = (num_time_steps, n_states)
    _t_before_breach: float,  unused
    t_after_breach: float
    _state_before_breach: NDArray, unused
    state_after_breach: NDArray
        Shape = (n_states,)
    next_store_index: int
    n_nodes: int
    _r: NDArray, unused
    _r_tilde: NDArray, unused

    Returns
    -------
    tuple[NDArray, float, NDArray, int, bool]
        (x_store, current_t, current_share, save_index, advances_time)
        advances_time=False
    """
    # Use projection onto simplex as reflection point.
    proj_after_breach = _project_onto_standard_simplex(state_after_breach)
    reflection = 2 * proj_after_breach - state_after_breach

    # If reflection is outside of boundary, modify reflection
    if (reflection <= 0).any():
        n_states = state_after_breach.shape[-1]
        reflection_direction = proj_after_breach - state_after_breach

        # If close to corner, i.e., intersection of all faces,
        # drag outside of corner into the middle of the simplex.
        # This approximates behavior of MFE reflection.
        if np.max(proj_after_breach) > 1 - 1 / n_nodes:
            modified_reflection_direction = (
                np.full(n_states, 1 / n_states) - proj_after_breach
            )
            modified_reflection_distance = np.linalg.norm(
                reflection_direction
            ) / np.linalg.norm(modified_reflection_direction)
            reflection_direction = (
                modified_reflection_direction * modified_reflection_distance
            )

        # Compute upper bound for allowed length of reflection
        # Since state_after_breach is on the hyperplane generated by the simplex,
        # the condition that the reflection is inside the simplex
        # reduces to the condition that all components of the reflection are nonnegative i.e.,
        # proj_after_breach + a * reflection_direction >= 0.
        # The upper bound is derived from this condition by solving for a.
        upper_bound = np.min(
            np.where(
                reflection_direction < 0,
                -proj_after_breach / reflection_direction,
                np.inf,
            )
        )
        # Reflect the allowed distance into the simplex.
        reflection = proj_after_breach + 0.99 * upper_bound * reflection_direction

    return x_store, t_after_breach, reflection, next_store_index, False


@njit(cache=True)
def simulate_boundary_jump_process(
    t_eval: NDArray,
    x_store: NDArray,
    t_before_breach: float,
    t_after_breach: float,
    state_before_breach: NDArray,
    state_after_breach: NDArray,
    next_store_index: int,
    n_nodes: int,
    r: NDArray,
    r_tilde: NDArray,
) -> tuple[NDArray, float, NDArray, int, bool]:
    """
    Simulates a jump process in the boundary until it jumps outside the boundary.

    Uses a slow variant of the Gillespie algorithm. Could be optimized.
    Always advances time.

    Parameters
    ----------
    t_eval: NDArray
        Shape = (num_timesteps,)
    x_store: NDArray
        Shape = (num_timesteps, n_states)
    t_before_breach: float
    t_after_breach: float
    state_before_breach: NDArray
        Shape = (n_states,)
    state_after_breach: NDArray
        Shape = (n_states,)
    next_store_index: int
    n_nodes: int
    r: NDArray
        Shape = (n_states, n_states)
    r_tilde: NDArray
        Shape = (n_states, n_states)

    Returns
    -------
    tuple[NDArray, float, NDArray, int, bool]
        (x_store, current_t, current_share, save_index, advances_time)
        advances_time = True
    """

    n_states = x_store.shape[1]

    # Compute the starting point of the boundary jump process.
    # If two sides are breached, the line between before_breach and after_breach will a.s. not hit the corner
    # This choice of starting point has no theoretical justification.
    # This choice + the design of the CLE algorithm ensures that the starting point is before the next t_eval time.

    breached_side_index = int(np.argmin(state_after_breach))

    initial_time, initial_share = _compute_intersection_with_boundary(
        breached_side_index,
        state_before_breach,
        state_after_breach,
        t_before_breach,
        t_after_breach,
    )

    propensities = np.zeros((n_states, n_states))
    current_t = initial_time
    current_shares = initial_share

    while True:
        _update_boundary_propensities(propensities, r, r_tilde, current_shares, n_nodes)

        sum_props = np.sum(propensities)
        current_t += np.random.exponential(1 / sum_props)
        cum_sum = np.cumsum(propensities / sum_props)
        reaction = np.searchsorted(cum_sum, np.random.random(), side="right")
        m, n = reaction // n_states, reaction % n_states

        while current_t >= t_eval[next_store_index]:
            x_store[next_store_index] = current_shares
            next_store_index += 1
            if next_store_index == len(t_eval):
                return x_store, current_t, current_shares, next_store_index, True

        current_shares[m] -= 1 / n_nodes
        current_shares[n] += 1 / n_nodes

        # Check if still in boundary
        if not (current_shares <= 0).any():
            return x_store, current_t, current_shares, next_store_index, True


@njit(cache=True)
def _compute_intersection_with_boundary(
    breached_side_index: int,
    state_before_breach: NDArray,
    state_after_breach: NDArray,
    t_before_breach: float,
    t_after_breach: float,
) -> tuple[float, NDArray]:
    s_star = state_before_breach[breached_side_index] / (
        state_before_breach[breached_side_index]
        - state_after_breach[breached_side_index]
    )
    initial_time = float(t_before_breach + s_star * (t_after_breach - t_before_breach))
    initial_share = state_before_breach + s_star * (
        state_after_breach - state_before_breach
    )
    return initial_time, initial_share


@njit(cache=True)
def _update_boundary_propensities(
    props: NDArray,
    r: NDArray,
    r_tilde: NDArray,
    c: NDArray,
    n_nodes: int,
):
    for m in range(props.shape[0]):
        for n in range(props.shape[1]):
            if m == n:
                continue
            if c[m] < 1 / n_nodes:
                props[m][n] = 0
                continue
            props[m, n] = c[m] * (r[m, n] * c[n] + r_tilde[m, n])
    props *= n_nodes


@njit(cache=True)
def _project_onto_standard_simplex(x: NDArray) -> NDArray:
    """
    Computes the best approximation of the standard d-1 simplex to a given point in R^d.

    Algorithm from https://doi.org/10.48550/arXiv.1101.6081
    Could be further sped up by using constant time median algorithm.

    Parameters
    ----------
    x: NDArray

    Returns
    -------
    NDArray
            shape=x.shape

    """
    n_states = x.shape[0]
    y = np.sort(x)
    index = n_states - 1
    while True:
        t = (np.sum(y[index:]) - 1) / (n_states - index)
        if t >= y[index - 1]:
            t_hat = t
            break
        index -= 1
        if index == 0:
            t_hat = (np.sum(y) - 1) / n_states
            break
    res = x - t_hat
    return np.where(res > 0, res, 0)


def _map_to_simplex_facette(x: NDArray, facette_index: int) -> NDArray:

    res = np.empty(x.shape[0] + 2)
    res[facette_index] = 0

    if facette_index == x.shape[0]:
        res[0] = 1 - np.sum(x)

    res[(facette_index + 1) % (res.shape[0] + 1)] = 1 - np.sum(x)


def get_boundary_process_from_alias(alias: str) -> BoundaryProcess:
    boundary_process_dict = {
        "clipping": clip_to_boundary,
        "jump": simulate_boundary_jump_process,
        "normal-reflection": compute_normal_boundary_reflection,
    }

    return boundary_process_dict[alias]
